In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as f

batch_size = 4
sequence_length = 64
embed_dim = 128

x = torch.randn(batch_size, sequence_length, embed_dim)
print("Shape of input is : ", x.shape)

Shape of input is :  torch.Size([4, 64, 128])


In [2]:
x.shape

torch.Size([4, 64, 128])

In [3]:
x.transpose(1, 2).shape

torch.Size([4, 128, 64])

In [4]:
similarity = (x @ x.transpose(1, 2))

In [5]:
similarity.shape

torch.Size([4, 64, 64])

In [6]:
similarity.var()

tensor(378.6302)

In [7]:
similarity = (x @ x.transpose(1, 2)) / (embed_dim ** 0.5)

similarity

tensor([[[ 1.0268e+01,  1.2565e+00, -8.2669e-01,  ...,  1.4863e-01,
          -1.1407e+00, -4.4333e-01],
         [ 1.2565e+00,  1.0766e+01,  2.9310e-01,  ...,  5.5962e-01,
          -5.8741e-01, -4.8319e-01],
         [-8.2669e-01,  2.9310e-01,  1.1365e+01,  ...,  1.2612e+00,
           1.4575e+00,  1.2807e+00],
         ...,
         [ 1.4863e-01,  5.5962e-01,  1.2612e+00,  ...,  1.1136e+01,
          -1.1884e+00,  9.9347e-01],
         [-1.1407e+00, -5.8741e-01,  1.4575e+00,  ..., -1.1884e+00,
           1.0129e+01,  1.4992e-01],
         [-4.4333e-01, -4.8319e-01,  1.2807e+00,  ...,  9.9347e-01,
           1.4992e-01,  9.8272e+00]],

        [[ 1.0972e+01,  1.1438e+00, -7.4626e-02,  ..., -3.4558e-02,
           1.1144e+00,  1.7002e-01],
         [ 1.1438e+00,  1.4216e+01,  8.7876e-01,  ...,  3.3719e-01,
           8.0250e-02, -6.5302e-02],
         [-7.4626e-02,  8.7876e-01,  8.6855e+00,  ..., -8.4962e-01,
           5.4566e-01,  6.3294e-01],
         ...,
         [-3.4558e-02,  3

In [8]:
attn_mat = similarity.softmax(dim = 2)

attn_mat

tensor([[[9.9619e-01, 1.2160e-04, 1.5142e-05,  ..., 4.0158e-05,
          1.1062e-05, 2.2217e-05],
         [7.3967e-05, 9.9804e-01, 2.8224e-05,  ..., 3.6844e-05,
          1.1701e-05, 1.2986e-05],
         [5.0635e-06, 1.5516e-05, 9.9865e-01,  ..., 4.0850e-05,
          4.9712e-05, 4.1657e-05],
         ...,
         [1.6896e-05, 2.5484e-05, 5.1398e-05,  ..., 9.9858e-01,
          4.4372e-06, 3.9327e-05],
         [1.2709e-05, 2.2100e-05, 1.7080e-04,  ..., 1.2116e-05,
          9.9625e-01, 4.6196e-05],
         [3.4451e-05, 3.3105e-05, 1.9318e-04,  ..., 1.4494e-04,
          6.2352e-05, 9.9460e-01]],

        [[9.9839e-01, 5.3848e-05, 1.5923e-05,  ..., 1.6574e-05,
          5.2290e-05, 2.0336e-05],
         [2.1021e-06, 9.9991e-01, 1.6127e-06,  ..., 9.3834e-07,
          7.2572e-07, 6.2742e-07],
         [1.5468e-04, 4.0132e-04, 9.8608e-01,  ..., 7.1263e-05,
          2.8762e-04, 3.1385e-04],
         ...,
         [4.1742e-05, 6.0538e-05, 1.8476e-05,  ..., 9.9521e-01,
          5.207

In [9]:
attn_mat.shape, x.shape

(torch.Size([4, 64, 64]), torch.Size([4, 64, 128]))

In [10]:
output = (attn_mat @ x)

output.shape

torch.Size([4, 64, 128])

In [11]:
linear = nn.Linear(10, 20)

rand = torch.randn(4, 6, 10)

linear(rand).shape

torch.Size([4, 6, 20])

In [12]:
#Single head attention

class Attention(nn.Module):
    def __init__(self, embedding_dimension):

        super().__init__()

        self.embed_dim = embedding_dimension

        self.query = nn.Linear(self.embed_dim, self.embed_dim)
        self.key = nn.Linear(self.embed_dim, self.embed_dim)
        self.value = nn.Linear(self.embed_dim, self.embed_dim)

    def forward(self, x):
        
        q = self.query(x)
        k = self.key(x)
        v = self.value(x)

        similarity = (q @ k.transpose(1, 2)) / self.embed_dim ** 0.5
        attention = similarity.softmax(axis=2)
        output = attention @ v

rand = torch.randn(4, 64, 128)

attn = Attention(embedding_dimension=128)
attn(rand)

In [13]:
class MultiHeadAttention(nn.Module):
    def __init__(self, embedding_dimension, num_heads):
        super().__init__()

        self.embed_dim = embedding_dimension
        self.num_heads = num_heads

        self.head_dim = self.embed_dim // self.num_heads

        self.multihead_qkv = nn.ModuleList()

        for head in range(num_heads):
            qkv_proj = nn.ModuleDict(
                [
                  ["Q", nn.Linear(self.embed_dim, self.head_dim)],
                  ["K", nn.Linear(self.embed_dim, self.head_dim)],
                  ["V", nn.Linear(self.embed_dim, self.head_dim)]  
                ]
            )

            self.multihead_qkv.append(qkv_proj)

        self.proj = nn.Linear(self.embed_dim, self.embed_dim)

    def forward(self, x):
        head_outs = []

        for head in self.multihead_qkv:

            q = head["Q"](x)
            k = head["K"](x)
            v = head["V"](x)

            similarity = (q @ k.transpose(1, 2)) / self.head_dim ** 0.5
            attention = similarity.softmax(axis=-1)
            output = attention @ v

            head_outs.append(output)

        head_outs = torch.cat(head_outs, dim=-1)

        out = self.proj(head_outs)

        return out
            

rand = torch.randn(4, 64, 128)
attn = MultiHeadAttention(128, 4)
attn(rand).shape

torch.Size([4, 64, 128])

In [14]:
fc = nn.Linear(10, 30)

tensor_1 = torch.randn(5, 10)
tensor_1_out = fc(tensor_1)

print("Inpur shape : ", tensor_1.shape, "Output shape : ", tensor_1_out.shape)

tensor_2 = torch.randn(5, 1, 2, 4, 10)
tensor_2_out = fc(tensor_2)

print("Inpur shape : ", tensor_2.shape, "Output shape : ", tensor_2_out.shape)

Inpur shape :  torch.Size([5, 10]) Output shape :  torch.Size([5, 30])
Inpur shape :  torch.Size([5, 1, 2, 4, 10]) Output shape :  torch.Size([5, 1, 2, 4, 30])


In [15]:
tensor = torch.rand(1, 8, 9)
fc = nn.Linear(9, 9)

q = fc(tensor)

chunk1, chun2, chunk3 = torch.chunk(q, 3, axis=-1)

In [16]:
a = torch.rand(1, 2, 6, 4)
b = torch.rand(1, 2, 4, 3)

a @ b

tensor([[[[0.6559, 0.2059, 0.6697],
          [0.6202, 0.1403, 0.4848],
          [0.4504, 0.1322, 0.4542],
          [0.6138, 0.1462, 0.2849],
          [0.3269, 0.1453, 0.1458],
          [0.7133, 0.2605, 0.7728]],

         [[0.5961, 1.1480, 1.1801],
          [0.4665, 0.5345, 0.6125],
          [0.7205, 0.7102, 0.9938],
          [0.9263, 1.1756, 1.3610],
          [0.8005, 0.7385, 1.1198],
          [1.2332, 1.6062, 1.8821]]]])

In [17]:
class SelfAttentionEncoder(nn.Module):
    def __init__(self, embed_dim, num_heads, attn_p = 0.0, proj_p = 0.0, bias = True):

        super().__init__()

        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.head_dim = embed_dim // num_heads

        self.query = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.key = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.value = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.attn_drop = nn.Dropout(attn_p)

        self.proj = nn.Linear(embed_dim, embed_dim)
        self.proj_drop = nn.Dropout(proj_p)


    def forward(self, x):
        batch_size, sequence_length, embed_dim = x.shape

        print(x.shape)

        q = self.query(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.key(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.value(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)
        
        attn = q @ k.transpose(-2, -1) * self.head_dim ** 0.5
        attn = attn.softmax(axis=-1)
        attn = self.attn_drop(attn)
        x = attn @ v

        x = x.transpose(1, 2).reshape(batch_size, sequence_length, embed_dim)
        print(x.shape)

        x = self.proj(x)
        x = self.proj_drop(x)


rand = torch.randn(4, 16, 128)
attn = SelfAttentionEncoder(128, 4)
attn(rand)

torch.Size([4, 16, 128])
torch.Size([4, 16, 128])


In [18]:
rand_attn = torch.rand(1, 6, 6)

attention_mask = torch.tensor([1, 1, 1, 1, 0, 0]).unsqueeze(0).bool()
print(attention_mask.shape)
attention_mask = attention_mask.unsqueeze(1).repeat(1, 6, 1)
print(attention_mask.shape, rand_attn.shape)

# torch.softmax(rand_attn.masked_fill(~attention_mask, -float("inf")), axis=-1)

attention_mask.shape, rand_attn.shape

torch.Size([1, 6])
torch.Size([1, 6, 6]) torch.Size([1, 6, 6])


(torch.Size([1, 6, 6]), torch.Size([1, 6, 6]))

In [19]:
rand_attn = torch.rand(1, 2, 6, 6)

attention_mask = torch.tensor([1, 1, 1, 1, 0, 0]).unsqueeze(0).bool()
attention_mask = attention_mask.unsqueeze(1).unsqueeze(1)
attention_mask = attention_mask.repeat(1, 2, 6, 1)
print(attention_mask)

# rand_attn.masked_fill_(~attention_mask, float("-inf"))

tensor([[[[ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False]],

         [[ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False],
          [ True,  True,  True,  True, False, False]]]])


In [20]:
class SelfAttention(nn.Module):
    def __init__(self, embed_dim, num_heads, attn_p = 0.0, proj_p = 0.0, bias = True):

        super().__init__()

        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.head_dim = embed_dim // num_heads

        self.query = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.key = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.value = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.attn_drop = nn.Dropout(attn_p)

        self.proj = nn.Linear(embed_dim, embed_dim)
        self.proj_drop = nn.Dropout(proj_p)


    def forward(self, x, attention_mask = None):
        batch_size, sequence_length, embed_dim = x.shape

        print(x.shape)

        q = self.query(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.key(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.value(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)

        attn = q @ k.transpose(-2, -1) * self.head_dim ** 0.5
        
        #############################################

        if attention_mask is not None:
            print("Attention mask")

            attention_mask = attention_mask.unsqueeze(1).unsqueeze(1) # .repeat(1, 1, sequence_length, 1) Optional
            print(attention_mask[0])
            print(attn[0])

            attn = attn.masked_fill_(~attention_mask, float("-inf"))
            print(attn)

        #############################################

        attn = attn.softmax(axis=-1)
        print(attn)
        attn = self.attn_drop(attn)
        x = attn @ v
        print(attn.shape)

        x = x.transpose(1, 2).reshape(batch_size, sequence_length, embed_dim)
        print(x.shape)

        x = self.proj(x)
        x = self.proj_drop(x)


seq_lens = [3, 5, 4]
embed_dim = 9
num_heads = 3

a = SelfAttention(embed_dim, num_heads)

rand = torch.randn(len(seq_lens), max(seq_lens), embed_dim)

masks = torch.nn.utils.rnn.pad_sequence([torch.ones(l) for l in seq_lens], batch_first=True, padding_value=0).bool()
print("Attention mask : ")
print(masks)

output = a(rand, masks)

Attention mask : 
tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]])
torch.Size([3, 5, 9])
Attention mask
tensor([[[ True,  True,  True, False, False]]])
tensor([[[-0.4550, -0.9569, -0.1710, -0.0531, -0.9505],
         [-1.7715, -2.6556, -0.5237, -0.1762, -3.8146],
         [-2.5309, -3.0199, -0.8909,  1.1515, -4.2274],
         [ 0.4121,  1.0369,  0.4669, -1.5741, -0.6938],
         [ 0.9171, -0.2411,  0.4634, -2.2436, -0.0156]],

        [[ 0.3537,  0.3328, -1.5118,  0.2724,  1.0875],
         [ 0.0137, -0.1634, -3.4248, -0.4824,  0.4855],
         [ 0.5322,  0.5548, -1.7498,  0.4510,  1.7862],
         [ 1.5191,  2.0694,  2.5023,  2.2602,  4.8753],
         [ 1.6590,  2.0132,  4.2559,  3.1314,  2.4365]],

        [[ 1.8559, -0.2740, -0.4152, -1.3188,  0.7285],
         [ 2.1710, -0.2695,  0.7326, -1.0444,  1.4451],
         [ 1.5628,  0.4426,  0.7797, -0.2022,  0.6660],
         [ 0.9694, -0.8699, -

In [21]:
seq_len = 8

ones = torch.ones(seq_len, seq_len)
causal_mask = torch.tril(ones).bool()

padding_mask = torch.tensor([1, 1, 1, 1, 0, 0, 0, 0]).bool()
padding_mask = padding_mask.unsqueeze(0).repeat(seq_len, 1)

causal_mask = causal_mask.masked_fill_(~padding_mask, 0)
causal_mask 

tensor([[ True, False, False, False, False, False, False, False],
        [ True,  True, False, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False],
        [ True,  True,  True,  True, False, False, False, False]])

In [22]:
class CausalSelfAttention(nn.Module):
    def __init__(self, embed_dim, num_heads, causal= True, attn_p = 0.0, proj_p = 0.0, bias = True):

        super().__init__()

        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.head_dim = embed_dim // num_heads
        self.causal = causal

        self.query = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.key = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.value = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.attn_drop = nn.Dropout(attn_p)

        self.proj = nn.Linear(embed_dim, embed_dim)
        self.proj_drop = nn.Dropout(proj_p)


    def forward(self, x, attention_mask = None):
        batch_size, sequence_length, embed_dim = x.shape


        q = self.query(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.key(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.value(x).reshape(batch_size, sequence_length, self.num_heads, self.head_dim).transpose(1, 2)

        attn = q @ k.transpose(-2, -1) * self.head_dim ** 0.5

        if attention_mask is not None:
                attention_mask = attention_mask.unsqueeze(1).unsqueeze(1) # .repeat(1, 1, sequence_length, 1) Optional
        
        if self.causal:

            ones = torch.ones((sequence_length, sequence_length), device=attn.device)
            causal_mask = torch.tril(ones).bool()
            causal_mask = causal_mask.unsqueeze(0).unsqueeze(0)
            print(causal_mask)

            if attention_mask is not None:

                causal_mask = causal_mask.repeat(batch_size, 1, 1, 1)
                causal_mask = causal_mask.masked_fill_(~attention_mask, False)
            

            attn = attn.masked_fill_(~causal_mask, float("-inf"))

        #############################################

        attn = attn.softmax(axis=-1)
        attn = self.attn_drop(attn)
        x = attn @ v

        x = x.transpose(1, 2).reshape(batch_size, sequence_length, embed_dim)

        x = self.proj(x)
        x = self.proj_drop(x)


seq_lens = [3, 5, 4]
embed_dim = 9
num_heads = 3

a = SelfAttention(embed_dim, num_heads)

rand = torch.randn(len(seq_lens), max(seq_lens), embed_dim)

masks = torch.nn.utils.rnn.pad_sequence([torch.ones(l) for l in seq_lens], batch_first=True, padding_value=0).bool()
print("Attention mask : ")
print(masks)

output = a(rand, masks)

Attention mask : 
tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]])
torch.Size([3, 5, 9])
Attention mask
tensor([[[ True,  True,  True, False, False]]])
tensor([[[ 3.5980,  3.0408, -0.3852,  1.5518,  1.3125],
         [ 1.0029,  0.9437, -0.1802,  0.4670,  0.2429],
         [ 4.1343,  3.2670, -0.5779,  1.7707,  1.3450],
         [ 2.9766,  2.4272, -0.1906,  1.2383,  1.2891],
         [-0.5812, -0.1905, -0.1584, -0.1445, -0.5862]],

        [[ 1.0826,  0.5311, -0.8726, -0.0258,  0.1584],
         [-0.1475, -0.2137,  0.2020,  0.2004,  0.0182],
         [ 0.0110,  0.3225, -0.3905,  0.6109, -0.7916],
         [ 1.3656,  0.9238, -1.3381,  0.0896, -0.1897],
         [-1.3821, -0.6339,  1.0005,  0.4438, -0.5304]],

        [[ 0.6494,  0.0209, -0.4285,  0.9724,  0.4905],
         [ 0.3025,  0.0570, -0.2345,  0.4699,  0.3621],
         [-0.1344,  0.0435, -0.3194, -0.0163, -0.0926],
         [ 0.7941, -0.1201, -

In [39]:
class CrossAttention(nn.Module):
    def __init__(self, embed_dim, num_heads, attn_p = 0.0, proj_p = 0.0, bias = True):

        super().__init__()

        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.head_dim = embed_dim // num_heads

        self.query = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.key = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.value = nn.Linear(embed_dim, embed_dim, bias=bias)
        self.attn_drop = nn.Dropout(attn_p)

        self.proj = nn.Linear(embed_dim, embed_dim)
        self.proj_drop = nn.Dropout(proj_p)


    def forward(self, src, tgt, attention_mask = None):
        batch_size, src_seq_len, embed_dim = src.shape
        batch_size, tgt_seq_len, embed_dim = tgt.shape

        print(tgt.shape)

        q = self.query(tgt).reshape(batch_size, tgt_seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.key(src).reshape(batch_size, src_seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.value(src).reshape(batch_size, src_seq_len, self.num_heads, self.head_dim).transpose(1, 2)

        attn = q @ k.transpose(-2, -1) * self.head_dim ** 0.5
        
        #############################################

        if attention_mask is not None:
            print("Attention mask")
            attention_mask = attention_mask.unsqueeze(1).unsqueeze(1).repeat(1, 1, tgt_seq_len, 1)
            print(attention_mask.shape)

            # attention_mask = attention_mask.unsqueeze(1).unsqueeze(1) # .repeat(1, 1, sequence_length, 1) Optional
            # print(attention_mask[0])
            # print(attn[0])

            # attn = attn.masked_fill_(~attention_mask, float("-inf"))
            # print(attn)

        #############################################

        attn = attn.softmax(axis=-1)
        attn = self.attn_drop(attn)
        x = attn @ v
        x = x.transpose(1, 2).reshape(batch_size, tgt_seq_len, embed_dim)
        print(x.shape)

        x = self.proj(x)
        x = self.proj_drop(x)

        return x


english_seq_lens = [3, 5, 4]
french_seq_lens = [7, 6, 2]

embed_dim = 18
num_heads = 3
a = CrossAttention(embed_dim, num_heads)

rand_english = torch.randn(len(english_seq_lens), max(english_seq_lens), embed_dim)
rand_french = torch.randn(len(french_seq_lens), max(french_seq_lens), embed_dim)

english_masks = torch.nn.utils.rnn.pad_sequence([torch.ones(l) for l in english_seq_lens], batch_first=True, padding_value=0).bool()
french_masks = torch.nn.utils.rnn.pad_sequence([torch.ones(l) for l in french_seq_lens], batch_first=True, padding_value=0).bool()

print("English Attention Mask : ")
print(english_masks)
print("French Attention Mask : ")
print(french_masks)

output = a(src=rand_english, tgt = rand_french, attention_mask=english_masks)
print("Final output : ", output.shape)

English Attention Mask : 
tensor([[ True,  True,  True, False, False],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True, False]])
French Attention Mask : 
tensor([[ True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True, False],
        [ True,  True, False, False, False, False, False]])
torch.Size([3, 7, 18])
Attention mask
torch.Size([3, 1, 7, 5])
torch.Size([3, 7, 18])
Final output :  torch.Size([3, 7, 18])
